import { ArrowUp, CheckCircle, ClockCountdown, Info, Leaf, PencilSimple, Recycle, ShieldCheck, Sparkle, Trash, UserPlus, WarningCircle, X } from '@phosphor-icons/react'
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { ECO_POINT_RULES, WEEKLY_CHALLENGES, getPeriodEnd, neutralNickname, validateNickname, type LeaderboardPeriod } from '../../shared/ecoPoints'
import type { Page } from '../components/AppShell'
import { KoalaMascot } from '../components/KoalaMascot'
import { SupabaseAuthPanel } from '../components/SupabaseAuthPanel'
import { useAccessibleDialog } from '../hooks/useAccessibleDialog'
import { useEcoMind } from '../state/EcoMindContext'
import { useSupabase } from '../state/SupabaseContext'

const periodLabels: Record<LeaderboardPeriod, string> = { week: 'This week', month: 'This month', all: 'All time' }
function timeRemaining() { const end = getPeriodEnd('week')!; const days = Math.max(0, Math.ceil((end.getTime() - Date.now()) / 86_400_000)); return days === 1 ? '1 day until Monday 00:00 UTC' : `${days} days until Monday 00:00 UTC` }

function ConfirmDialog({ open, title, children, confirmLabel, danger = false, onClose, onConfirm }: { open: boolean; title: string; children: ReactNode; confirmLabel: string; danger?: boolean; onClose: () => void; onConfirm: () => void }) {
  const ref = useAccessibleDialog(open, onClose)
  if (!open) return null
  return createPortal(<div className="modal-layer" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section ref={ref} className="modal leaderboard-leave" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><button data-dialog-initial className="icon-button modal__close" onClick={onClose} aria-label="Close confirmation"><X size={21} /></button><ShieldCheck size={32} weight="duotone" /><h2 id="confirm-title">{title}</h2><div>{children}</div><div><button className="button button--secondary" onClick={onClose}>Cancel</button><button className={`button ${danger ? 'button--danger' : 'button--primary'}`} onClick={onConfirm}>{confirmLabel}</button></div></section></div>, document.body)
}

export function LeaderboardPage({ navigate }: { navigate: (page: Page) => void }) {
  const { pointEvents, recordEcoAction } = useEcoMind()
  const backend = useSupabase()
  const [period, setPeriod] = useState<LeaderboardPeriod>('week')
  const [nickname, setNickname] = useState(neutralNickname())
  const [error, setError] = useState<string | null>(null)
  const [editing, setEditing] = useState(false)
  const [confirm, setConfirm] = useState<'leave' | 'delete' | 'import' | null>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => { if (backend.profile?.displayName) setNickname(backend.profile.displayName) }, [backend.profile?.displayName])
  const current = backend.rankings.find((entry) => entry.isCurrentUser)
  const weekKey = new Date(getPeriodEnd('week')!.getTime() - 1).toISOString().slice(0, 10)
  const queueForUser = backend.queue.filter((item) => item.accountId === backend.user?.id)
  const community = useMemo(() => ({ actions: backend.rankings.reduce((sum, entry) => sum + entry.actionCount, 0) }), [backend.rankings])

  const saveProfile = async () => {
    const validation = validateNickname(nickname); setError(validation); if (validation) return
    try { if (backend.profile?.optedIn) await backend.updateNickname(nickname); else await backend.join(nickname); setEditing(false) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save the profile.') }
  }
  const claimChallenge = (challenge: typeof WEEKLY_CHALLENGES[number]) => recordEcoAction({ key: `weekly-${weekKey}-${challenge.id}`, actionType: 'completeWeeklyChallenge', title: challenge.title, detail: challenge.description, source: challenge.selfReported ? 'self-reported' : 'web', selfReported: challenge.selfReported, metadata: { challengeId: challenge.id } })

  return <div className="leaderboard-page page-surface">
    <header className="page-hero container leaderboard-header"><div><p className="kicker">EcoMind Community</p><h1>Small actions, shared progress.</h1><p>Rankings use EcoPoints from mindful choices, repair, reuse and challenges—not how much someone buys.</p></div><div className={`prototype-flag${backend.liveVerified ? ' is-live' : ''}`}><Info size={19} /><span>{backend.liveVerified ? 'Live EcoMind community leaderboard' : backend.configured ? 'Backend connected · verification pending' : 'Backend setup required'}<br /><small>{backend.liveVerified ? 'Rankings contain opted-in members only.' : 'No fictional participants are shown.'}</small></span></div></header>
    <div className="container leaderboard-content">
      <SupabaseAuthPanel />

      {backend.user && !backend.profile?.optedIn && <section className="leaderboard-join" aria-labelledby="join-title"><div><UserPlus size={30} weight="duotone" /><h2 id="join-title">Join the EcoMind leaderboard</h2><p>Participation is optional. Only your nickname, koala level, badge, EcoPoints and meaningful-action count become public.</p><ul><li>Email remains private</li><li>No product titles or shopping history</li><li>No purchase information, age, location or school</li><li>Leave without deleting private points</li></ul></div><form onSubmit={(event) => { event.preventDefault(); void saveProfile() }}><label htmlFor="leaderboard-name">Choose a nickname</label><input ref={inputRef} id="leaderboard-name" value={nickname} onChange={(event) => setNickname(event.target.value)} maxLength={20} aria-invalid={Boolean(error)} />{error && <p role="alert">{error}</p>}<button className="button button--primary" type="submit">Join leaderboard</button><p className="join-consent">Basic safeguards apply. Self-reported actions are not independently verified.</p></form></section>}

      {backend.user && backend.localImportAvailable(pointEvents) && <section className="sync-prompt"><div><ArrowUp size={22} /><div><h2>Import your local EcoMind progress?</h2><p>Only recognised point actions, timestamps and deduplication keys will be uploaded. Wishlist, product pages, browsing history and legacy balances stay local.</p></div></div><button className="button button--secondary" onClick={() => setConfirm('import')}>Review import</button></section>}

      {backend.profile?.optedIn && backend.summary && <><section className="leaderboard-summary" aria-label="Your current leaderboard summary"><div><span>Current rank</span><strong>{backend.summary.rank ? `#${backend.summary.rank}` : '—'}</strong><small>{backend.summary.pointsToNextRank ? `${backend.summary.pointsToNextRank} points to the next position` : 'You lead this period'}</small></div><div><span>Weekly EcoPoints</span><strong>{period === 'week' ? backend.summary.periodPoints : '—'}</strong><small>{timeRemaining()}</small></div><div><span>Actions this period</span><strong>{backend.summary.periodActions}</strong><small>Server-confirmed actions</small></div><div><span>Koala level</span><KoalaMascot size={49} points={backend.summary.allTimePoints} /><strong>{backend.summary.koalaLevel}</strong><small>{backend.summary.badge}</small></div><button className="profile-edit" onClick={() => setEditing(true)}><PencilSimple size={17} /> Edit nickname</button></section>{editing && <form className="inline-profile-form" onSubmit={(event) => { event.preventDefault(); void saveProfile() }}><label htmlFor="leaderboard-name-edit">Nickname</label><input ref={inputRef} id="leaderboard-name-edit" value={nickname} onChange={(event) => setNickname(event.target.value)} maxLength={20} />{error && <p role="alert">{error}</p>}<button className="button button--primary">Save</button><button className="button button--secondary" type="button" onClick={() => setEditing(false)}>Cancel</button></form>}</>}

      <section className="leaderboard-board" aria-labelledby="ranking-title"><div className="leaderboard-board__heading"><div><h2 id="ranking-title">Community ranking</h2><p><ClockCountdown size={16} /> {period === 'week' ? timeRemaining() : `${periodLabels[period]} · UTC`}</p></div><div className="period-tabs" role="tablist" aria-label="Leaderboard period">{(['week', 'month', 'all'] as LeaderboardPeriod[]).map((item) => <button key={item} role="tab" aria-selected={period === item} onClick={() => { setPeriod(item); void backend.refresh(item) }}>{periodLabels[item]}</button>)}</div><button className="button button--text" onClick={() => void backend.refresh(period)}>Refresh</button></div>
        {backend.backendState === 'loading' && <div className="leaderboard-empty" role="status"><span className="loading-orbit" /><h3>Loading rankings…</h3><p>Fetching server-confirmed EcoPoints.</p></div>}
        {backend.backendState === 'offline' && <div className="leaderboard-empty"><WarningCircle size={30} /><h3>You are offline</h3><p>Recorded actions stay in the queue and will be validated when the connection returns.</p></div>}
        {backend.backendState === 'error' && <div className="leaderboard-empty"><WarningCircle size={30} /><h3>Leaderboard unavailable</h3><p>{backend.message ?? 'Try refreshing shortly. Local product analysis still works.'}</p></div>}
        {backend.backendState === 'unconfigured' && <div className="leaderboard-empty"><ShieldCheck size={30} /><h3>Community backend is not configured</h3><p>No sample people are substituted. Follow the Supabase setup guide to enable real rankings.</p></div>}
        {backend.backendState === 'ready' && backend.rankings.length === 0 && <div className="leaderboard-empty"><Leaf size={30} /><h3>No community members have joined this period yet.</h3><p>Be the first to take part.</p></div>}
        {backend.backendState === 'ready' && backend.rankings.length > 0 && <><ol className="leaderboard-podium" aria-label="Top three community positions">{backend.rankings.slice(0, 3).map((entry) => <li key={entry.publicId} className={`podium-entry podium-entry--${entry.rank}`}><span className="podium-position" aria-label={`Position ${entry.rank}`}>{entry.rank}</span><KoalaMascot size={entry.rank === 1 ? 74 : 62} points={entry.ecoPoints} /><div><h3>{entry.displayName}</h3><p>{entry.koalaLevel}</p><strong>{entry.ecoPoints} EcoPoints</strong><small>{entry.actionCount} meaningful actions · {entry.badge}</small></div></li>)}</ol><div className="ranking-table" role="table" aria-label={`${periodLabels[period]} EcoMind leaderboard`}><div className="ranking-row ranking-row--header" role="row"><span role="columnheader">Rank</span><span role="columnheader">Participant</span><span role="columnheader">EcoPoints</span><span role="columnheader">Actions</span><span role="columnheader">Badge</span></div>{backend.rankings.map((entry) => <div className={`ranking-row${entry.isCurrentUser ? ' ranking-row--current' : ''}`} role="row" key={entry.publicId} aria-label={`${entry.displayName}, rank ${entry.rank}${entry.isCurrentUser ? ', your profile' : ''}`}><strong role="cell">#{entry.rank}</strong><span role="cell"><KoalaMascot size={38} points={entry.ecoPoints} /><span><b>{entry.displayName}{entry.isCurrentUser ? ' · You' : ''}</b><small>{entry.koalaLevel}</small></span></span><strong role="cell">{entry.ecoPoints}</strong><span role="cell">{entry.actionCount}</span><span role="cell">{entry.badge}</span></div>)}</div>{current && current.rank > 5 && <div className="current-user-pin"><ArrowUp size={18} /><span>Your row: <strong>#{current.rank} · {current.displayName}</strong></span><b>{current.ecoPoints} points</b></div>}</>}
      </section>

      {backend.user && <section className="weekly-challenges"><div className="section-heading"><h2>Weekly actions</h2><p>Backend validation limits every challenge to one claim per Monday–Sunday UTC period.</p></div><div className="weekly-challenge-list">{WEEKLY_CHALLENGES.map((challenge) => { const key = `weekly-${weekKey}-${challenge.id}`; const queued = queueForUser.find((item) => item.deduplicationKey === key); const localPrerequisite = challenge.selfReported || pointEvents.some((event) => event.actionType === challenge.progressActionType); return <article key={challenge.id}><span className="challenge-status">{queued?.status === 'synced' ? <CheckCircle size={22} weight="fill" /> : challenge.id === 'repair-reuse' ? <Recycle size={22} /> : challenge.id === 'compare-products' ? <Leaf size={22} /> : <Sparkle size={22} />}</span><div><h3>{challenge.title}</h3><p>{challenge.description}</p><small>{challenge.selfReported ? 'Self-reported · ' : ''}+30 server-controlled EcoPoints{queued ? ` · ${queued.status.replaceAll('_', ' ')}` : ''}</small></div><button disabled={Boolean(queued) || !localPrerequisite} onClick={() => claimChallenge(challenge)}>{queued?.status === 'synced' ? 'Synced' : queued ? 'Waiting' : !localPrerequisite ? 'Compare first' : 'Complete'}</button></article> })}</div></section>}

      {queueForUser.length > 0 && <section className="sync-queue"><div><h2>Synchronisation</h2><p>Actions remain visible until Supabase confirms, rejects or rate-limits them.</p></div><ul>{queueForUser.slice(0, 6).map((item) => <li key={item.id}><span>{item.deduplicationKey}</span><strong>{item.status.replaceAll('_', ' ')}</strong></li>)}</ul><button className="button button--secondary" onClick={() => void backend.syncQueue()}>Sync now</button></section>}

      <section className="community-context"><div><h2>Community context</h2><p>Only backend-confirmed actions from opted-in members are counted. EcoMind does not claim verified environmental savings.</p></div><dl><div><dt>Meaningful actions</dt><dd>{community.actions}</dd></div><div><dt>Members this period</dt><dd>{backend.rankings.length}</dd></div></dl></section>
      <details className="ranking-explanation"><summary><Info size={18} /> How ranking works</summary><div><p>Week starts Monday 00:00 UTC; month starts on day one 00:00 UTC. Ties use points, then meaningful-action count, then the earlier time reaching the current score.</p><p>Scans and purchases earn zero. Point values come from a protected database function. Repeatable and self-reported actions are limited. Rankings encourage participation, not consumption.</p><p>EcoMind uses basic safeguards in this prototype. A production rewards programme would require stronger verification, moderation and abuse detection.</p><ul>{Object.entries(ECO_POINT_RULES).map(([key, value]) => <li key={key}><span>{key.replace(/([A-Z])/g, ' $1').toLowerCase()}</span><strong>+{value}</strong></li>)}</ul></div></details>
      {backend.user && <div className="leaderboard-exit">{backend.profile?.optedIn && <button onClick={() => setConfirm('leave')}>Leave leaderboard</button>}<button className="button button--secondary" onClick={() => navigate('dashboard')}>View dashboard</button><button className="button button--text account-delete" onClick={() => setConfirm('delete')}><Trash size={16} /> Delete account data</button></div>}
    </div>
    <ConfirmDialog open={confirm === 'leave'} title="Leave the leaderboard?" confirmLabel="Leave leaderboard" onClose={() => setConfirm(null)} onConfirm={() => { void backend.leave(); setConfirm(null) }}><p>Your public row will disappear. Your private account, events and local wishlist stay available.</p></ConfirmDialog>
    <ConfirmDialog open={confirm === 'delete'} title="Delete your EcoMind account?" confirmLabel="Delete account and data" danger onClose={() => setConfirm(null)} onConfirm={() => { void backend.deleteAccount(); setConfirm(null) }}><p>This permanently deletes the Supabase profile, point events, challenge completions and backend preferences. Local guest data is not automatically deleted.</p></ConfirmDialog>
    <ConfirmDialog open={confirm === 'import'} title="Import local actions?" confirmLabel="Import recognised actions" onClose={() => setConfirm(null)} onConfirm={() => { void backend.importLocalProgress(pointEvents); setConfirm(null) }}><p>EcoMind uploads action type, deduplication key, source and timestamp for recognised events. The server recalculates points. Product and browsing data are excluded.</p></ConfirmDialog>
  </div>
}
